name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM depencdencies
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display softuni name
      run: echo "stanimir1912"

  run-ui-tests:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM depencdencies
      run: npm install
    - name: Install Plywright Browsers
      run: npx playwright install
    - name: Start application
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui
